In [95]:
import numpy as np
import pandas as pd

In [96]:
df = pd.read_csv("/content/heart (1).csv")

In [97]:
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [98]:
from sklearn.preprocessing import LabelEncoder

In [99]:
from sklearn.preprocessing import LabelEncoder

sex_encoder = LabelEncoder()
chest_encoder = LabelEncoder()
ecg_encoder = LabelEncoder()
angina_encoder = LabelEncoder()
slope_encoder = LabelEncoder()

df['Sex'] = sex_encoder.fit_transform(df['Sex'])
df['ChestPainType'] = chest_encoder.fit_transform(df['ChestPainType'])
df['RestingECG'] = ecg_encoder.fit_transform(df['RestingECG'])
df['ExerciseAngina'] = angina_encoder.fit_transform(df['ExerciseAngina'])
df['ST_Slope'] = slope_encoder.fit_transform(df['ST_Slope'])

In [100]:
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,1,1,140,289,0,1,172,0,0.0,2,0
1,49,0,2,160,180,0,1,156,0,1.0,1,1
2,37,1,1,130,283,0,2,98,0,0.0,2,0
3,48,0,0,138,214,0,1,108,1,1.5,1,1
4,54,1,2,150,195,0,1,122,0,0.0,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,3,110,264,0,1,132,0,1.2,1,1
914,68,1,0,144,193,1,1,141,0,3.4,1,1
915,57,1,0,130,131,0,1,115,1,1.2,1,1
916,57,0,1,130,236,0,0,174,0,0.0,1,1
917,38,1,2,138,175,0,1,173,0,0.0,2,0

In [101]:
x = df.drop('HeartDisease', axis = 1)
y= df['HeartDisease']

In [102]:
x.columns

Index(['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope'],
      dtype='object')

In [103]:
from sklearn.preprocessing import StandardScaler

In [104]:
model = StandardScaler()

In [105]:
cols = ['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope']
df[cols] = model.fit_transform(df[cols])

In [106]:
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,-1.433140,0.515952,0.229032,0.410909,0.825070,-0.551341,0.017255,1.382928,-0.823556,-0.832432,1.052114,0
1,-0.478484,-1.938163,1.275059,1.491752,-0.171961,-0.551341,0.017255,0.754157,-0.823556,0.105664,-0.596078,1
2,-1.751359,0.515952,0.229032,-0.129513,0.770188,-0.551341,1.601219,-1.525138,-0.823556,-0.832432,1.052114,0
3,-0.584556,-1.938163,-0.816995,0.302825,0.139040,-0.551341,0.017255,-1.132156,1.214246,0.574711,-0.596078,1
4,0.051881,0.515952,1.275059,0.951331,-0.034755,-0.551341,0.017255,-0.581981,-0.823556,-0.832432,1.052114,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,-0.902775,0.515952,2.321086,-1.210356,0.596393,-0.551341,0.017255,-0.188999,-0.823556,0.293283,-0.596078,1
914,1.536902,0.515952,-0.816995,0.627078,-0.053049,1.813758,0.017255,0.164684,-0.823556,2.357094,-0.596078,1
915,0.370100,0.515952,-0.816995,-0.129513,-0.620168,-0.551341,0.017255,-0.857069,1.214246,0.293283,-0.596078,1
916,0.370100,-1.938163,0.229032,-0.129513,0.340275,-0.551341,-1.566710,1.461525,-0.823556,-0.832432,-0.596078,1
917,-1.645286,0.515952,1.275059,0.302825,-0.217696,-0.551341,0.017255,1.422226,-0.823556,-0.832432,1.052114,0

# Instead of using train_test_split use cross validation

In [107]:
from sklearn.model_selection import cross_val_score

In [108]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size = 0.2, random_state = 42)

In [150]:
from sklearn.svm import SVC
model_svm = SVC(kernel='rbf')

In [151]:
scores = cross_val_score(model_svm,x,y,cv=5 , scoring='accuracy')
scores

array([0.60869565, 0.78804348, 0.69021739, 0.71584699, 0.61748634])

In [152]:
scores.mean()

np.float64(0.6840579710144927)

In [153]:
model_svm.fit(x_train,y_train)

SVC()

In [154]:
y_pred = model_svm.predict(x_test)

In [155]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [156]:
accuracy_score(y_test,y_pred)

0.6847826086956522

In [116]:
from sklearn.naive_bayes import GaussianNB

In [117]:
model_NB = GaussianNB()

In [118]:
scores = cross_val_score(model_NB,x,y,cv=5)
scores

array([0.83152174, 0.9076087 , 0.79891304, 0.8579235 , 0.75956284])

In [119]:
model_NB.fit(x_train,y_train)

GaussianNB()

In [120]:
y_pred_NB = model_NB.predict(x_test)

In [121]:
accuracy_score(y_test,y_pred_NB)

0.842391304347826

In [122]:
from sklearn.neighbors import KNeighborsClassifier

In [157]:
Model_knn = KNeighborsClassifier(n_neighbors=5 , weights='distance')

In [158]:
scores = cross_val_score(Model_knn,x,y,cv=5)
scores

array([0.61413043, 0.76630435, 0.66304348, 0.64480874, 0.63387978])

In [159]:
Model_knn.fit(x_train,y_train)

KNeighborsClassifier(weights='distance')

In [160]:
y_pred_knn = Model_knn.predict(x_test)

In [161]:
accuracy_score(y_test,y_pred_knn)

0.6956521739130435

In [128]:
# Decision tree

In [129]:
from sklearn.tree import DecisionTreeClassifier

In [130]:
model_tree = DecisionTreeClassifier(random_state=42)

In [131]:
scores = cross_val_score(model_tree,x,y,cv=5)
scores

array([0.77173913, 0.75      , 0.79347826, 0.74863388, 0.67759563])

In [132]:
model_tree.fit(x_train,y_train)

DecisionTreeClassifier(random_state=42)

In [133]:
y_pred_tree= model_tree.predict(x_test)

In [134]:
accuracy_score(y_test,y_pred_tree)

0.782608695652174

In [135]:
# logistic_regression

In [136]:
from sklearn.linear_model import LogisticRegression

In [137]:
model_LG =LogisticRegression()

In [ ]:
scores = cross_val_score(model_LG,x,y,cv=5)
scores

In [ ]:
model_LG.fit(x_train , y_train)

In [140]:
y_pred_lg = model_LG.predict(x_test)

In [141]:
accuracy_score(y_test,y_pred_lg)

0.842391304347826

In [142]:
# linear regression

In [143]:
from sklearn.linear_model import LinearRegression

In [144]:
model_lr = LinearRegression()

In [145]:
scores = cross_val_score(model_lr,x,y,cv=5)
scores

array([0.4823843 , 0.54735838, 0.31926714, 0.33603904, 0.38194081])

In [146]:
model_lr.fit(x_train,y_train)

LinearRegression()

In [147]:
y_pred_lr = model_lr.predict(x_test)

In [148]:
from sklearn.metrics import r2_score

In [149]:
r2_score(y_test,y_pred_lr)

0.4358397138678326