In [93]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [94]:
df = sns.load_dataset('iris')

In [95]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [96]:
df['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [97]:
from sklearn.model_selection import train_test_split

In [98]:
x= df.drop('species' , axis = 1)
y=df['species']

In [99]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [100]:
from sklearn.neighbors import KNeighborsClassifier

In [101]:
model_knn = KNeighborsClassifier()

In [102]:
model_knn.fit(x_train , y_train)

KNeighborsClassifier(n_neighbors=9)

In [103]:
model_knn.score(x_test , y_test)

1.0

In [104]:
from sklearn.svm import SVC

In [105]:
model_svm = SVC(C=1 , gamma='auto')

In [106]:
model_svm.fit(x_train,y_train)

SVC(C=1, gamma='auto')

In [107]:
model_svm.score(x_test,y_test)

0.9666666666666667

# GRID seach CV

In [108]:
from sklearn.model_selection import GridSearchCV

In [109]:
classifier = GridSearchCV(model_svm,
                          {'C' : [1,10,20,30],
                           'kernel' : ['rbf' , 'linear'],
                           'gamma' : ['auto' , 'scale']
                          }, cv=5, return_train_score=False)

In [110]:
classifier.fit(x,y)

GridSearchCV(cv=5, estimator=SVC(C=1, gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'linear']})

In [112]:
results = pd.DataFrame(classifier.cv_results_)

In [ ]:
results

In [ ]:
results[['param_C', 'param_kernel' , 'mean_test_score']]

Check GridSeachCV using KNN

In [117]:
classifier = GridSearchCV(model_knn,{
    'n_neighbors':[3,5,7,9,11,13,15,17,19,21],
    'weights':['uniform', 'distance'],
    'algorithm':['auto' , 'auto', 'ball_tree', 'kd_tree', 'brute'],
    'metric':['minkowski', 'euclidean', 'manhattan']
}, cv=5, return_train_score=False)

In [118]:
classifier.fit(x,y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=9),
             param_grid={'algorithm': ['auto', 'auto', 'ball_tree', 'kd_tree',
                                       'brute'],
                         'metric': ['minkowski', 'euclidean', 'manhattan'],
                         'n_neighbors': [3, 5, 7, 9, 11, 13, 15, 17, 19, 21],
                         'weights': ['uniform', 'distance']})

In [119]:
results = pd.DataFrame(classifier.cv_results_)

In [120]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_metric,param_n_neighbors,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005070,0.000921,0.007497,0.002522,auto,minkowski,3,uniform,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,186
1,0.004738,0.001278,0.005379,0.001003,auto,minkowski,3,distance,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,186
2,0.003998,0.000206,0.005638,0.000149,auto,minkowski,5,uniform,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,58
3,0.004034,0.000113,0.004262,0.000103,auto,minkowski,5,distance,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,186
4,0.003715,0.000177,0.005137,0.000141,auto,minkowski,7,uniform,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,0.003692,0.000185,0.004151,0.000247,brute,manhattan,17,distance,"{'algorithm': 'brute', 'metric': 'manhattan', ...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,58
296,0.003657,0.000280,0.005368,0.000496,brute,manhattan,19,uniform,"{'algorithm': 'brute', 'metric': 'manhattan', ...",0.933333,1.000000,0.966667,0.966667,1.0,0.973333,0.024944,58
297,0.004033,0.000517,0.004335,0.000197,brute,manhattan,19,distance,"{'algorithm': 'brute', 'metric': 'manhattan', ...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,58
298,0.003547,0.000084,0.005274,0.000159,brute,manhattan,21,uniform,"{'algorithm': 'brute', 'metric': 'manhattan', ...",0.933333,1.000000,0.966667,0.966667,1.0,0.973333,0.024944,58
299,0.006377,0.003420,0.007514,0.003340,brute,manhattan,21,distance,"{'algorithm': 'brute', 'metric': 'manhattan', ...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,58

In [ ]:
results[['params','rank_test_score']]