In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [73]:
df = pd.read_csv("/content/data_cleaned.csv")

In [74]:
df

     survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0           0       3    1   22      1      0     7         2      0
1           1       1    0   38      1      0    71         0      0
2           1       3    0   26      0      0     7         2      1
3           1       1    0   35      1      0    53         2      0
4           0       3    1   35      0      0     8         2      1
..        ...     ...  ...  ...    ...    ...   ...       ...    ...
886         0       2    1   27      0      0    13         2      1
887         1       1    0   19      0      0    30         2      1
888         0       3    0   29      1      2    23         2      0
889         1       1    1   26      0      0    30         0      1
890         0       3    1   32      0      0     7         1      1

[891 rows x 9 columns]

In [75]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'alone'],
      dtype='object')

In [76]:
from sklearn.preprocessing import StandardScaler

cols = [ 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'alone']

scaler = StandardScaler()

df[cols] = scaler.fit_transform(df[cols])

In [77]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,alone
0,0,0.827377,0.737695,-0.580044,0.432793,-0.473674,-0.498948,0.585954,-1.231645
1,1,-1.566107,-1.355574,0.650112,0.432793,-0.473674,0.789405,-1.942303,-1.231645
2,1,0.827377,-1.355574,-0.272505,-0.474545,-0.473674,-0.498948,0.585954,0.811922
3,1,-1.566107,-1.355574,0.419458,0.432793,-0.473674,0.427056,0.585954,-1.231645
4,0,0.827377,0.737695,0.419458,-0.474545,-0.473674,-0.478817,0.585954,0.811922
...,...,...,...,...,...,...,...,...,...
886,0,-0.369365,0.737695,-0.195620,-0.474545,-0.473674,-0.378164,0.585954,0.811922
887,1,-1.566107,-1.355574,-0.810699,-0.474545,-0.473674,-0.035946,0.585954,0.811922
888,0,0.827377,-1.355574,-0.041851,0.432793,2.008933,-0.176859,0.585954,-1.231645
889,1,-1.566107,0.737695,-0.272505,-0.474545,-0.473674,-0.035946,-1.942303,0.811922
890,0,0.827377,0.737695,0.188804,-0.474545,-0.473674,-0.498948,-0.678175,0.811922

In [78]:
df['pclass'].value_counts()

pclass
 0.827377    491
-1.566107    216
-0.369365    184
Name: count, dtype: int64

In [79]:
x  = df.drop('survived', axis = 1)
y = df['survived']

In [80]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

In [81]:
from sklearn.neighbors import KNeighborsClassifier

In [128]:
model = KNeighborsClassifier(n_neighbors=51)

In [129]:
model.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=51)

In [130]:
y_pred = model.predict(x_test)

In [131]:
from sklearn.metrics import accuracy_score, confusion_matrix , classification_report

In [132]:
accuracy_score(y_test, y_pred)

0.8100558659217877

In [107]:
confusion_matrix(y_test, y_pred)

array([[92, 13],
       [23, 51]])

In [101]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.83      0.86      0.84       105
           1       0.79      0.74      0.76        74

    accuracy                           0.81       179
   macro avg       0.81      0.80      0.80       179
weighted avg       0.81      0.81      0.81       179