In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [5]:
df = pd.read_csv("/content/Cleaned_data1.csv")

In [6]:
df

,age,sex,bmi,children,smoker,charges,region_northeast,region_northwest,region_southeast,region_southwest,bmi_category_Underweight,bmi_category_Normal,bmi_category_Overweight,bmi_category_Obese
0,-1.440418,1,-0.517949,0,1,16884,0,0,0,1,0,0,1,0
1,-1.511647,0,0.462463,1,0,1725,0,0,1,0,0,0,0,1
2,-0.799350,0,0.462463,3,0,4449,0,0,1,0,0,0,0,1
3,-0.443201,0,-1.334960,0,0,21984,0,1,0,0,0,1,0,0
4,-0.514431,0,-0.354547,0,0,3866,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1332,0.767704,0,-0.027743,3,0,10600,0,1,0,0,0,0,0,1
1333,-1.511647,1,0.135659,0,0,2205,1,0,0,0,0,0,0,1
1334,-1.511647,1,0.952670,0,0,1629,0,0,1,0,0,0,0,1
1335,-1.297958,1,-0.844753,0,0,2007,0,0,0,1,0,0,1,0
1336,1.551231,1,-0.191145,0,1,29141,0,1,0,0,0,0,1,0

In [7]:
df.head()

,age,sex,bmi,children,smoker,charges,region_northeast,region_northwest,region_southeast,region_southwest,bmi_category_Underweight,bmi_category_Normal,bmi_category_Overweight,bmi_category_Obese
0,-1.440418,1,-0.517949,0,1,16884,0,0,0,1,0,0,1,0
1,-1.511647,0,0.462463,1,0,1725,0,0,1,0,0,0,0,1
2,-0.799350,0,0.462463,3,0,4449,0,0,1,0,0,0,0,1
3,-0.443201,0,-1.334960,0,0,21984,0,1,0,0,0,1,0,0
4,-0.514431,0,-0.354547,0,0,3866,0,1,0,0,0,0,1,0

In [8]:
from sklearn.model_selection import train_test_split

In [11]:
x = df.drop('charges', axis = 1)
y=df['charges']

In [12]:
y

0       16884
1        1725
2        4449
3       21984
4        3866
        ...
1332    10600
1333     2205
1334     1629
1335     2007
1336    29141
Name: charges, Length: 1337, dtype: int64

In [13]:
x

,age,sex,bmi,children,smoker,region_northeast,region_northwest,region_southeast,region_southwest,bmi_category_Underweight,bmi_category_Normal,bmi_category_Overweight,bmi_category_Obese
0,-1.440418,1,-0.517949,0,1,0,0,0,1,0,0,1,0
1,-1.511647,0,0.462463,1,0,0,0,1,0,0,0,0,1
2,-0.799350,0,0.462463,3,0,0,0,1,0,0,0,0,1
3,-0.443201,0,-1.334960,0,0,0,1,0,0,0,1,0,0
4,-0.514431,0,-0.354547,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1332,0.767704,0,-0.027743,3,0,0,1,0,0,0,0,0,1
1333,-1.511647,1,0.135659,0,0,1,0,0,0,0,0,0,1
1334,-1.511647,1,0.952670,0,0,0,0,1,0,0,0,0,1
1335,-1.297958,1,-0.844753,0,0,0,0,0,1,0,0,1,0
1336,1.551231,1,-0.191145,0,1,0,1,0,0,0,0,1,0

In [14]:
X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.20, random_state=42)

In [20]:
X_train.shape

(1069, 13)

In [21]:
X_test.shape

(268, 13)

In [22]:
df.shape

(1337, 14)

In [23]:
from sklearn.linear_model import LinearRegression

In [24]:
model = LinearRegression()

In [25]:

model.fit(X_train, y_train)

LinearRegression()

In [26]:
y_pred = model.predict(X_test)

In [28]:
y_pred

array([ 8166.78502481,  5258.38131296, 14497.99789106, 32423.6640176 ,
        8891.26581447, 13244.63457082, 30592.05118176,   979.84902293,
       11114.85682058, 10108.52380939, 10622.44251544, 32202.41254134,
       31975.49437307, 15697.09485972, 10645.35025208,  8303.83848414,
        5209.89541151, 32402.5675715 ,  2919.305424  ,  3980.50684962,
        4747.32918081, 29354.63599137, 13695.56304609, 29346.00605159,
       31419.5514214 ,  6326.29710096, 34873.7723571 , 37501.87867079,
       12910.61613546, 14641.39890665,  8014.78112639, 12948.46999436,
         435.70439017, 11129.53428269, 37304.88988202, 12975.93018524,
        3578.01505238,  4454.36647644, 31336.0564352 ,  8087.5739297 ,
        6438.55737161, 30726.84991053, 35211.61181082, 13512.72092791,
        7852.72704398,  2842.21462578,  5533.412083  ,  7399.45168833,
        3661.69324597, 10381.31072588,  7802.6750964 , 10815.24872451,
       30889.18486887,  4696.70778781, 11331.12137502, 11452.69627431,
        9906.65584113,  2378.10983901, 31663.6625427 , 10961.52498394,
       14700.43413509,  9064.381994  , 13801.52623233,  1156.17285514,
       15107.77853149, 10367.60704478, 10711.10621871, 29708.68508748,
       23797.44485707, 16592.90642565,  6019.30764073,  4732.79791846,
        6818.89928385,  -763.17830261, 10429.45770993,  -239.42450459,
       15566.41205026,  9143.68491764,  7932.2762855 , 11660.96609126,
        7491.97925759, 16382.11249888, 15507.2154274 , 11606.70168031,
       35432.87497439, 11861.40199735,  4031.73155389,  1220.56701769,
        5975.39404254,  5355.55140016, 16176.17359667, 27837.05602004,
        5119.36895117,  4753.60800214,   865.68378874, 36685.4247384 ,
       13465.15443625,  8007.51251325,  5189.31114035,  8426.6336581 ,
       15148.89979835, 15401.87251193, 32089.26691384, 14662.96748313,
       33459.49211566,   227.15071923, 32358.5962857 , 26299.79038761,
       14700.55409404,  5218.29405229,  9779.20593344, 10668.40011416,
        9456.27524082, 10535.09031937,  5640.40101004,  5842.03732579,
        1444.97815957,  4204.10443528,  6076.10414824,  8910.44567643,
       36590.45456084,  8777.00875174, 11550.72135321, 10098.69310645,
        8008.94457541, 10844.63544939,  4300.40250591, 11210.35419195,
       29304.78828584, 38691.71217486, 34629.87185365, 12023.4345093 ,
        2081.96683301, 10405.44687866,  9947.6781837 ,  6982.72434582,
       34369.0541097 , 30430.68533407, 24205.14003399,  5732.53588588,
        5232.59950212,  4502.32441309, 34515.51002663, 10485.43803702,
        4844.59576691,  9317.7209844 ,  9161.64858009,  7485.63053169,
       35242.56881989, 15679.57311411, 10316.47464649,  6838.56366778,
        8664.23630615, 16035.69280625,  6781.36306601, 27563.47138233,
       34173.41526191, 14155.28285556, 11483.65328338, 12253.4303978 ,
       13759.78109698,  4775.30037698, 13948.10210821, 14354.52661738,
       37010.54598599, 34770.99165537, 13959.45851027, 24586.05139164,
        2386.22760385,  2737.61401461,  4349.97688177,  4735.094327  ,
        4242.4757798 ,  9715.86516466, 11504.74972947, 25160.58908217,
        1740.63056109, 11643.77611628,  7505.94107452, 13698.62557165,
       16047.68134219,  5980.26962431, 10439.57226685,  9797.35864328,
       33988.41141136,  9878.87369236,  7353.97861158,  6953.67152931,
         357.83352869, 31764.30823032,  7337.58523332, 32250.82180891,
       13593.54083716,  4719.41187842,  1206.79424814,  3963.92018592,
       33865.84636675,  4087.26996414, 12294.36681017, 17295.49551129,
       27600.46089485, 25303.07991108,  8367.91033527, 13317.26645715,
       27062.77650576,  8708.74027225, 11252.3306263 , 11337.23880192,
        2127.90286127, 34220.28767885, 30764.17756948,  9129.43453123,
        4885.65213823,  6993.53935409, 10368.5913501 ,  4655.03291055,
        5401.48742842, 11336.05025537,  8567.30389457,  4732.79791846,
        3091.02881492, 36510.9467548 , 35606.55995899, 12743.38608384,
       12634.34175545, 38596.42542134, 35706.33546024,  5773.00596446,
       27984.80465261,  3719.11966026, 15441.68527329, 30937.91225494,
        7266.99983994, 10166.12745311,  7670.71723018,  8008.43240048,
        8460.24365198,  4494.91007764,  6306.63271703,  6447.35982533,
        6867.49268595,  6262.12875094,  4648.14179617,  8260.85150365,
         851.89051384,  8289.35006942,  3346.15280991, 11380.98427521,
        1446.9784975 , 11996.5945892 ,  5131.1046628 , 10726.38077919,
       10913.43112268, 15749.85889105, 37595.9992192 , 23513.81552186,
       10187.81982794,  9562.11846811,  7942.43011599, 13808.88550437,
       29794.40699512, 38510.24657798, 15733.43314433, 16094.41145873,
       15578.48550965,  7123.1827948 , 38610.8922656 ,  7884.92589818])

In [29]:
from sklearn.metrics import r2_score


r2 = r2_score(y_test, y_pred)

In [30]:
r2

0.802640025212984

In [33]:
n = X_test.shape[0]
p = X_test.shape[1]

In [34]:
adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)

In [35]:
adjusted_r2

0.7925389241412076